# render.yaml - Production-ready configuration for Render.com
databases:
  - name: social_media_db       
    plan: free                 
    databaseName: socialmedia 
    user: socialmedia         

services:
  - type: web
    plan: free
    name: social_media_api     
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput  # Runs even without static files
    startCommand: |
      python -m gunicorn social_media_api.wsgi:application --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"        # Always False in production
      - key: ALLOWED_HOSTS
        value: ".onrender.com" # Render's domain
      - key: WEB_CONCURRENCY
        value: "4"          