databases:
  - name: social_media_db
    plan: free
    databaseName: socialmedia
    user: socialmedia

services:
  - type: web
    plan: free
    name: social_media_api
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn social_media_api.wsgi:application --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"