# render.yaml - PRODUCTION-READY CONFIG
databases:
  - name: social_media_db
    plan: free
    databaseName: socialmedia
    user: socialmedia

services:
  - type: web
    plan: free
    name: social_media_api
    runtime: python
    python:
      version: "3.11.11"
      usePoetry: false 
    
    # Build commands
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python social_media_api/manage.py migrate
    
    # Startup command
    startCommand: gunicorn social_media_api.wsgi:application --workers 4 --bind 0.0.0.0:$PORT
    
    # Environment variables (Render will auto-generate/inject these)
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.social_media_api.settings
      
      - key: SECRET_KEY
        generateValue: true 
      
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      
      - key: DEBUG
        value: "False" 
      
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 
      
      - key: WEB_CONCURRENCY
        value: "4"  