# Generated by Django 5.1.7 on 2025-03-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='accounts.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
