# Generated by Django 5.1.7 on 2025-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
